baseURL = "http://example.org/"
languageCode = "en-us"
title = "Thavanathan"
theme = "whiteplain"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"
[[menu.main]]
    name = "Tutorials"
    weight = 30
    url = "/pages/tutorials/"
[[menu.main]]
    name = "About"
    weight = 40
    url = "/about/"